/*
Zinc Search engine API

Zinc Search engine API documents https://docs.zincsearch.com

API version: 0.2.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// V1ZincQuery struct for V1ZincQuery
type V1ZincQuery struct {
	Source []string `json:"_source,omitempty"`
	Aggs *map[string]V1AggregationParams `json:"aggs,omitempty"`
	Explain *bool `json:"explain,omitempty"`
	From *int32 `json:"from,omitempty"`
	Highlight *MetaHighlight `json:"highlight,omitempty"`
	MaxResults *int32 `json:"max_results,omitempty"`
	Query *V1QueryParams `json:"query,omitempty"`
	// SearchType is the type of search to perform. Can be match, match_phrase, query_string, etc
	SearchType *string `json:"search_type,omitempty"`
	SortFields []string `json:"sort_fields,omitempty"`
}

// NewV1ZincQuery instantiates a new V1ZincQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ZincQuery() *V1ZincQuery {
	this := V1ZincQuery{}
	return &this
}

// NewV1ZincQueryWithDefaults instantiates a new V1ZincQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ZincQueryWithDefaults() *V1ZincQuery {
	this := V1ZincQuery{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *V1ZincQuery) GetSource() []string {
	if o == nil || o.Source == nil {
		var ret []string
		return ret
	}
	return o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetSourceOk() ([]string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *V1ZincQuery) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given []string and assigns it to the Source field.
func (o *V1ZincQuery) SetSource(v []string) {
	o.Source = v
}

// GetAggs returns the Aggs field value if set, zero value otherwise.
func (o *V1ZincQuery) GetAggs() map[string]V1AggregationParams {
	if o == nil || o.Aggs == nil {
		var ret map[string]V1AggregationParams
		return ret
	}
	return *o.Aggs
}

// GetAggsOk returns a tuple with the Aggs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetAggsOk() (*map[string]V1AggregationParams, bool) {
	if o == nil || o.Aggs == nil {
		return nil, false
	}
	return o.Aggs, true
}

// HasAggs returns a boolean if a field has been set.
func (o *V1ZincQuery) HasAggs() bool {
	if o != nil && o.Aggs != nil {
		return true
	}

	return false
}

// SetAggs gets a reference to the given map[string]V1AggregationParams and assigns it to the Aggs field.
func (o *V1ZincQuery) SetAggs(v map[string]V1AggregationParams) {
	o.Aggs = &v
}

// GetExplain returns the Explain field value if set, zero value otherwise.
func (o *V1ZincQuery) GetExplain() bool {
	if o == nil || o.Explain == nil {
		var ret bool
		return ret
	}
	return *o.Explain
}

// GetExplainOk returns a tuple with the Explain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetExplainOk() (*bool, bool) {
	if o == nil || o.Explain == nil {
		return nil, false
	}
	return o.Explain, true
}

// HasExplain returns a boolean if a field has been set.
func (o *V1ZincQuery) HasExplain() bool {
	if o != nil && o.Explain != nil {
		return true
	}

	return false
}

// SetExplain gets a reference to the given bool and assigns it to the Explain field.
func (o *V1ZincQuery) SetExplain(v bool) {
	o.Explain = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *V1ZincQuery) GetFrom() int32 {
	if o == nil || o.From == nil {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetFromOk() (*int32, bool) {
	if o == nil || o.From == nil {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *V1ZincQuery) HasFrom() bool {
	if o != nil && o.From != nil {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *V1ZincQuery) SetFrom(v int32) {
	o.From = &v
}

// GetHighlight returns the Highlight field value if set, zero value otherwise.
func (o *V1ZincQuery) GetHighlight() MetaHighlight {
	if o == nil || o.Highlight == nil {
		var ret MetaHighlight
		return ret
	}
	return *o.Highlight
}

// GetHighlightOk returns a tuple with the Highlight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetHighlightOk() (*MetaHighlight, bool) {
	if o == nil || o.Highlight == nil {
		return nil, false
	}
	return o.Highlight, true
}

// HasHighlight returns a boolean if a field has been set.
func (o *V1ZincQuery) HasHighlight() bool {
	if o != nil && o.Highlight != nil {
		return true
	}

	return false
}

// SetHighlight gets a reference to the given MetaHighlight and assigns it to the Highlight field.
func (o *V1ZincQuery) SetHighlight(v MetaHighlight) {
	o.Highlight = &v
}

// GetMaxResults returns the MaxResults field value if set, zero value otherwise.
func (o *V1ZincQuery) GetMaxResults() int32 {
	if o == nil || o.MaxResults == nil {
		var ret int32
		return ret
	}
	return *o.MaxResults
}

// GetMaxResultsOk returns a tuple with the MaxResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetMaxResultsOk() (*int32, bool) {
	if o == nil || o.MaxResults == nil {
		return nil, false
	}
	return o.MaxResults, true
}

// HasMaxResults returns a boolean if a field has been set.
func (o *V1ZincQuery) HasMaxResults() bool {
	if o != nil && o.MaxResults != nil {
		return true
	}

	return false
}

// SetMaxResults gets a reference to the given int32 and assigns it to the MaxResults field.
func (o *V1ZincQuery) SetMaxResults(v int32) {
	o.MaxResults = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *V1ZincQuery) GetQuery() V1QueryParams {
	if o == nil || o.Query == nil {
		var ret V1QueryParams
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetQueryOk() (*V1QueryParams, bool) {
	if o == nil || o.Query == nil {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *V1ZincQuery) HasQuery() bool {
	if o != nil && o.Query != nil {
		return true
	}

	return false
}

// SetQuery gets a reference to the given V1QueryParams and assigns it to the Query field.
func (o *V1ZincQuery) SetQuery(v V1QueryParams) {
	o.Query = &v
}

// GetSearchType returns the SearchType field value if set, zero value otherwise.
func (o *V1ZincQuery) GetSearchType() string {
	if o == nil || o.SearchType == nil {
		var ret string
		return ret
	}
	return *o.SearchType
}

// GetSearchTypeOk returns a tuple with the SearchType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetSearchTypeOk() (*string, bool) {
	if o == nil || o.SearchType == nil {
		return nil, false
	}
	return o.SearchType, true
}

// HasSearchType returns a boolean if a field has been set.
func (o *V1ZincQuery) HasSearchType() bool {
	if o != nil && o.SearchType != nil {
		return true
	}

	return false
}

// SetSearchType gets a reference to the given string and assigns it to the SearchType field.
func (o *V1ZincQuery) SetSearchType(v string) {
	o.SearchType = &v
}

// GetSortFields returns the SortFields field value if set, zero value otherwise.
func (o *V1ZincQuery) GetSortFields() []string {
	if o == nil || o.SortFields == nil {
		var ret []string
		return ret
	}
	return o.SortFields
}

// GetSortFieldsOk returns a tuple with the SortFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ZincQuery) GetSortFieldsOk() ([]string, bool) {
	if o == nil || o.SortFields == nil {
		return nil, false
	}
	return o.SortFields, true
}

// HasSortFields returns a boolean if a field has been set.
func (o *V1ZincQuery) HasSortFields() bool {
	if o != nil && o.SortFields != nil {
		return true
	}

	return false
}

// SetSortFields gets a reference to the given []string and assigns it to the SortFields field.
func (o *V1ZincQuery) SetSortFields(v []string) {
	o.SortFields = v
}

func (o V1ZincQuery) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Source != nil {
		toSerialize["_source"] = o.Source
	}
	if o.Aggs != nil {
		toSerialize["aggs"] = o.Aggs
	}
	if o.Explain != nil {
		toSerialize["explain"] = o.Explain
	}
	if o.From != nil {
		toSerialize["from"] = o.From
	}
	if o.Highlight != nil {
		toSerialize["highlight"] = o.Highlight
	}
	if o.MaxResults != nil {
		toSerialize["max_results"] = o.MaxResults
	}
	if o.Query != nil {
		toSerialize["query"] = o.Query
	}
	if o.SearchType != nil {
		toSerialize["search_type"] = o.SearchType
	}
	if o.SortFields != nil {
		toSerialize["sort_fields"] = o.SortFields
	}
	return json.Marshal(toSerialize)
}

type NullableV1ZincQuery struct {
	value *V1ZincQuery
	isSet bool
}

func (v NullableV1ZincQuery) Get() *V1ZincQuery {
	return v.value
}

func (v *NullableV1ZincQuery) Set(val *V1ZincQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ZincQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ZincQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ZincQuery(val *V1ZincQuery) *NullableV1ZincQuery {
	return &NullableV1ZincQuery{value: val, isSet: true}
}

func (v NullableV1ZincQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ZincQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


