/*
Zinc Search engine API

Zinc Search engine API documents https://docs.zincsearch.com

API version: 0.2.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// V1AggregationNumberRange struct for V1AggregationNumberRange
type V1AggregationNumberRange struct {
	From *float32 `json:"from,omitempty"`
	To *float32 `json:"to,omitempty"`
}

// NewV1AggregationNumberRange instantiates a new V1AggregationNumberRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AggregationNumberRange() *V1AggregationNumberRange {
	this := V1AggregationNumberRange{}
	return &this
}

// NewV1AggregationNumberRangeWithDefaults instantiates a new V1AggregationNumberRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AggregationNumberRangeWithDefaults() *V1AggregationNumberRange {
	this := V1AggregationNumberRange{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *V1AggregationNumberRange) GetFrom() float32 {
	if o == nil || o.From == nil {
		var ret float32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AggregationNumberRange) GetFromOk() (*float32, bool) {
	if o == nil || o.From == nil {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *V1AggregationNumberRange) HasFrom() bool {
	if o != nil && o.From != nil {
		return true
	}

	return false
}

// SetFrom gets a reference to the given float32 and assigns it to the From field.
func (o *V1AggregationNumberRange) SetFrom(v float32) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *V1AggregationNumberRange) GetTo() float32 {
	if o == nil || o.To == nil {
		var ret float32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AggregationNumberRange) GetToOk() (*float32, bool) {
	if o == nil || o.To == nil {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *V1AggregationNumberRange) HasTo() bool {
	if o != nil && o.To != nil {
		return true
	}

	return false
}

// SetTo gets a reference to the given float32 and assigns it to the To field.
func (o *V1AggregationNumberRange) SetTo(v float32) {
	o.To = &v
}

func (o V1AggregationNumberRange) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.From != nil {
		toSerialize["from"] = o.From
	}
	if o.To != nil {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullableV1AggregationNumberRange struct {
	value *V1AggregationNumberRange
	isSet bool
}

func (v NullableV1AggregationNumberRange) Get() *V1AggregationNumberRange {
	return v.value
}

func (v *NullableV1AggregationNumberRange) Set(val *V1AggregationNumberRange) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AggregationNumberRange) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AggregationNumberRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AggregationNumberRange(val *V1AggregationNumberRange) *NullableV1AggregationNumberRange {
	return &NullableV1AggregationNumberRange{value: val, isSet: true}
}

func (v NullableV1AggregationNumberRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AggregationNumberRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


