/*
Zinc Search engine API

Zinc Search engine API documents https://docs.zincsearch.com

API version: 0.2.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AggregationHistogramBound struct for AggregationHistogramBound
type AggregationHistogramBound struct {
	// maximum
	Max *float32 `json:"max,omitempty"`
	// minimum
	Min *float32 `json:"min,omitempty"`
}

// NewAggregationHistogramBound instantiates a new AggregationHistogramBound object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregationHistogramBound() *AggregationHistogramBound {
	this := AggregationHistogramBound{}
	return &this
}

// NewAggregationHistogramBoundWithDefaults instantiates a new AggregationHistogramBound object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregationHistogramBoundWithDefaults() *AggregationHistogramBound {
	this := AggregationHistogramBound{}
	return &this
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *AggregationHistogramBound) GetMax() float32 {
	if o == nil || o.Max == nil {
		var ret float32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregationHistogramBound) GetMaxOk() (*float32, bool) {
	if o == nil || o.Max == nil {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *AggregationHistogramBound) HasMax() bool {
	if o != nil && o.Max != nil {
		return true
	}

	return false
}

// SetMax gets a reference to the given float32 and assigns it to the Max field.
func (o *AggregationHistogramBound) SetMax(v float32) {
	o.Max = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *AggregationHistogramBound) GetMin() float32 {
	if o == nil || o.Min == nil {
		var ret float32
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregationHistogramBound) GetMinOk() (*float32, bool) {
	if o == nil || o.Min == nil {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *AggregationHistogramBound) HasMin() bool {
	if o != nil && o.Min != nil {
		return true
	}

	return false
}

// SetMin gets a reference to the given float32 and assigns it to the Min field.
func (o *AggregationHistogramBound) SetMin(v float32) {
	o.Min = &v
}

func (o AggregationHistogramBound) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Max != nil {
		toSerialize["max"] = o.Max
	}
	if o.Min != nil {
		toSerialize["min"] = o.Min
	}
	return json.Marshal(toSerialize)
}

type NullableAggregationHistogramBound struct {
	value *AggregationHistogramBound
	isSet bool
}

func (v NullableAggregationHistogramBound) Get() *AggregationHistogramBound {
	return v.value
}

func (v *NullableAggregationHistogramBound) Set(val *AggregationHistogramBound) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregationHistogramBound) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregationHistogramBound) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregationHistogramBound(val *AggregationHistogramBound) *NullableAggregationHistogramBound {
	return &NullableAggregationHistogramBound{value: val, isSet: true}
}

func (v NullableAggregationHistogramBound) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregationHistogramBound) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


