/*
Zinc Search engine API

Zinc Search engine API documents https://docs.zincsearch.com

API version: 0.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// MetaDateRange struct for MetaDateRange
type MetaDateRange struct {
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
}

// NewMetaDateRange instantiates a new MetaDateRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaDateRange() *MetaDateRange {
	this := MetaDateRange{}
	return &this
}

// NewMetaDateRangeWithDefaults instantiates a new MetaDateRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaDateRangeWithDefaults() *MetaDateRange {
	this := MetaDateRange{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *MetaDateRange) GetFrom() string {
	if o == nil || o.From == nil {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaDateRange) GetFromOk() (*string, bool) {
	if o == nil || o.From == nil {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *MetaDateRange) HasFrom() bool {
	if o != nil && o.From != nil {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *MetaDateRange) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *MetaDateRange) GetTo() string {
	if o == nil || o.To == nil {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaDateRange) GetToOk() (*string, bool) {
	if o == nil || o.To == nil {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *MetaDateRange) HasTo() bool {
	if o != nil && o.To != nil {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *MetaDateRange) SetTo(v string) {
	o.To = &v
}

func (o MetaDateRange) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.From != nil {
		toSerialize["from"] = o.From
	}
	if o.To != nil {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullableMetaDateRange struct {
	value *MetaDateRange
	isSet bool
}

func (v NullableMetaDateRange) Get() *MetaDateRange {
	return v.value
}

func (v *NullableMetaDateRange) Set(val *MetaDateRange) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaDateRange) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaDateRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaDateRange(val *MetaDateRange) *NullableMetaDateRange {
	return &NullableMetaDateRange{value: val, isSet: true}
}

func (v NullableMetaDateRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaDateRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


