/*
Zinc Search engine API

Zinc Search engine API documents https://docs.zincsearch.com

API version: 0.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// MetaAggregationMetric struct for MetaAggregationMetric
type MetaAggregationMetric struct {
	Field *string `json:"field,omitempty"`
	// Field name to be used for setting weight for primary field for weighted average aggregation
	WeightField *string `json:"weight_field,omitempty"`
}

// NewMetaAggregationMetric instantiates a new MetaAggregationMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetaAggregationMetric() *MetaAggregationMetric {
	this := MetaAggregationMetric{}
	return &this
}

// NewMetaAggregationMetricWithDefaults instantiates a new MetaAggregationMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetaAggregationMetricWithDefaults() *MetaAggregationMetric {
	this := MetaAggregationMetric{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *MetaAggregationMetric) GetField() string {
	if o == nil || o.Field == nil {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAggregationMetric) GetFieldOk() (*string, bool) {
	if o == nil || o.Field == nil {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *MetaAggregationMetric) HasField() bool {
	if o != nil && o.Field != nil {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *MetaAggregationMetric) SetField(v string) {
	o.Field = &v
}

// GetWeightField returns the WeightField field value if set, zero value otherwise.
func (o *MetaAggregationMetric) GetWeightField() string {
	if o == nil || o.WeightField == nil {
		var ret string
		return ret
	}
	return *o.WeightField
}

// GetWeightFieldOk returns a tuple with the WeightField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetaAggregationMetric) GetWeightFieldOk() (*string, bool) {
	if o == nil || o.WeightField == nil {
		return nil, false
	}
	return o.WeightField, true
}

// HasWeightField returns a boolean if a field has been set.
func (o *MetaAggregationMetric) HasWeightField() bool {
	if o != nil && o.WeightField != nil {
		return true
	}

	return false
}

// SetWeightField gets a reference to the given string and assigns it to the WeightField field.
func (o *MetaAggregationMetric) SetWeightField(v string) {
	o.WeightField = &v
}

func (o MetaAggregationMetric) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Field != nil {
		toSerialize["field"] = o.Field
	}
	if o.WeightField != nil {
		toSerialize["weight_field"] = o.WeightField
	}
	return json.Marshal(toSerialize)
}

type NullableMetaAggregationMetric struct {
	value *MetaAggregationMetric
	isSet bool
}

func (v NullableMetaAggregationMetric) Get() *MetaAggregationMetric {
	return v.value
}

func (v *NullableMetaAggregationMetric) Set(val *MetaAggregationMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableMetaAggregationMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableMetaAggregationMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetaAggregationMetric(val *MetaAggregationMetric) *NullableMetaAggregationMetric {
	return &NullableMetaAggregationMetric{value: val, isSet: true}
}

func (v NullableMetaAggregationMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetaAggregationMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


